# This is a weird way of telling Travis to use the fast container-based test
# runner instead of the slow VM-based runner.
sudo: false

language: go

go:
  - 1.10.x

# Only clone the most recent commit.
git:
  depth: 1

before_script:
  - go get -u golang.org/x/vgo
  - vgo list -m | awk '{ print $1 }' | grep -v MODULE | xargs go get -u
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  # - golangci-lint run ./...
  - gometalinter --vendor --deadline=120s ./...
  - go test -v -timeout 1s -race ./... -coverprofile=coverage.out # Run all the tests with the race detector enabled
  - goveralls -coverprofile=coverage.out -service travis-ci